const mongoose = require('mongoose');

// Payment Schema
const paymentSchema = new mongoose.Schema(
{
    // Customer who makes the payment
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },

    // Service provider who receives the payment
    providerId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'ServiceProvider',
        required: true
    },

    // Service request associated with this payment
    // One service request should have only one payment
    requestId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'ServiceRequest',
        required: true,
        unique: true
    },

    // Total payment amount
    amount: {
        type: Number,
        required: true
    },

    // Currency used for the payment
    currency: {
        type: String,
        default: 'INR'
    },

    // Payment method
    method: {
        type: String,
        enum: ['cash', 'upi', 'card', 'netbanking', 'wallet'],
        required: true
    },

    // Transaction ID generated by the payment gateway
    transactionId: {
        type: String,
        default: null
    },

    // Date and time when the transaction was completed
    transactionDate: {
        type: Date,
        default: null
    },

    // Current payment status
    status: {
        type: String,
        enum: ['pending', 'completed', 'failed', 'refunded'],
        default: 'pending'
    },

    // Payment amount breakdown
    breakdown: {
        // Base service charge
        baseCharge: {
            type: Number,
            default: 0
        },

        // Charge based on travel distance
        distanceCharge: {
            type: Number,
            default: 0
        },

        // Applicable tax
        tax: {
            type: Number,
            default: 0
        },

        // Discount applied
        discount: {
            type: Number,
            default: 0
        },

        // Final payable amount
        total: {
            type: Number,
            default: 0
        }
    },

    // Refund details (if refunded)
    refund: {
        // Refunded amount
        amount: {
            type: Number,
            default: null
        },

        // Reason for refund
        reason: {
            type: String,
            default: null
        },

        // Date of refund
        refundedAt: {
            type: Date,
            default: null
        }
    },

    // Payment receipt URL
    receiptUrl: {
        type: String,
        default: null
    },

    // Additional payment notes
    notes: {
        type: String,
        default: null
    }

},
{
    // Automatically adds createdAt and updatedAt fields
    timestamps: true
}
);

// Export Payment model
module.exports = mongoose.model('Payment', paymentSchema);